"""Patch cell 11 of activation_rank_pipeline.ipynb with all-layer ablation experiment."""
import json
from pathlib import Path

NB = Path("notebooks/activation_rank_pipeline.ipynb")
CELL_SOURCE = (
    "# 11. 消融实验：所有层同时消融 — 排除\"后层修复前层\"假说\n"
    "# 方案1: 所有12层同时消融, 统一 K = max(各层单层99%恢复所需K)\n"
    "# 方案2: 所有12层同时消融, 扫描K网格, 画全层恢复曲线 vs 单层曲线\n"
    "from contextlib import ExitStack\n"
    "from src.activation_rank_loss_recovery import (\n"
    "    _load_candidate, _tokenize_evaluation, resolve_projection_module,\n"
    "    SingleSiteProjection, select_disjoint_evaluation_reports,\n"
    "    load_loss_recovery_policy,\n"
    ")\n"
    "from src.activation_rank import _model_paths, _mapping, _read_report_texts, _run_directory\n"
    "\n"
    "# --- 从 cell 10 结果读取各层 K_99 ---\n"
    "k99_per_layer = loss_recovery_summary.set_index('layer')['n_sustained_recovery'].dropna().astype(int).to_dict()\n"
    "k_unified = max(k99_per_layer.values())\n"
    "print('各层单层 99% 恢复所需 K:')\n"
    "for l in sorted(k99_per_layer):\n"
    "    print(f'  Layer {l:2d}: K_99 = {k99_per_layer[l]}')\n"
    "print(f'\\n方案1 统一 K = max(K_99) = {k_unified}')\n"
    "\n"
    "# --- 加载模型 + 评估数据 (与 cell 10 一致) ---\n"
    "run_dir = _run_directory(config)\n"
    "base, checkpoint = _model_paths(config)\n"
    "device = str(_mapping(config, 'model').get('device', 'cuda:1'))\n"
    "pilot_manifest = json.loads((run_dir / 'pilot' / 'manifest.json').read_text(encoding='utf-8'))\n"
    "dtype_name = pilot_manifest['selected_compute_dtype']\n"
    "candidate, tokenizer = _load_candidate(base=base, checkpoint=checkpoint, device=device, dtype_name=dtype_name)\n"
    "\n"
    "policy = load_loss_recovery_policy(ROOT / 'configs' / 'activation_rank_loss_recovery.yaml')\n"
    "reports = _read_report_texts(config)\n"
    "rank_sample = pd.read_parquet(run_dir / 'sample' / 'sample_manifest.parquet')\n"
    "selected = select_disjoint_evaluation_reports(\n"
    "    reports, rank_sample,\n"
    "    report_count=int(policy['evaluation']['report_count']),\n"
    "    order_seed=str(policy['evaluation']['order_seed']),\n"
    ")\n"
    "encoded = _tokenize_evaluation(tokenizer, selected, int(_mapping(config, 'model').get('max_length', 512)))\n"
    "\n"
    "# SVD 基 (12 层各有自己的主成分矩阵)\n"
    "sub = np.load(run_dir / 'analysis' / 'subspaces.npz', allow_pickle=False)\n"
    "all_layers = list(range(1, 13))\n"
    "bases = {f'attention_output_{l:02d}': sub[f'token_natural_filtered__attention_output_{l:02d}__eigenvectors'] for l in all_layers}\n"
    "modules = [(l, resolve_projection_module(candidate.bert, f'attention_output_{l:02d}')) for l in all_layers]\n"
    "\n"
    "# 基线 CLS\n"
    "baseline_parts = []\n"
    "with torch.inference_mode():\n"
    "    for start in range(0, len(selected), 256):\n"
    "        stop = min(start + 256, len(selected))\n"
    "        inputs = {k: v[start:stop].pin_memory().to(device, non_blocking=True) for k, v in encoded.items()}\n"
    "        out = candidate(**inputs)\n"
    "        baseline_parts.append(out.pooled_feature.float().cpu())\n"
    "baseline_cls = torch.cat(baseline_parts, dim=0)\n"
    "\n"
    "def all_layer_distance(k):\n"
    "    \"\"\"同时消融所有12层 attention output 到 k 维, 返回平均 CLS L2 距离.\"\"\"\n"
    "    with ExitStack() as stack:\n"
    "        if k < 768:\n"
    "            for layer, module in modules:\n"
    "                site = f'attention_output_{layer:02d}'\n"
    "                stack.enter_context(SingleSiteProjection(module, bases[site], k))\n"
    "        with torch.inference_mode():\n"
    "            parts = []\n"
    "            for start in range(0, len(selected), 256):\n"
    "                stop = min(start + 256, len(selected))\n"
    "                inputs = {key: v[start:stop].pin_memory().to(device, non_blocking=True) for key, v in encoded.items()}\n"
    "                out = candidate(**inputs)\n"
    "                parts.append(out.pooled_feature.float().cpu())\n"
    "    modified_cls = torch.cat(parts, dim=0)\n"
    "    distances = ((modified_cls - baseline_cls) ** 2).sum(dim=1)\n"
    "    return float(distances.mean().item())\n"
    "\n"
    "# 零消融基准 (所有层同时清零)\n"
    "dist_zero_all = all_layer_distance(0)\n"
    "print(f'\\n所有层同时零消融 distance = {dist_zero_all:.4f}')\n"
    "\n"
    "# --- 方案1: 统一 K = max(K_99) ---\n"
    "dist_k_unified = all_layer_distance(k_unified)\n"
    "recovery_scheme1 = 1 - dist_k_unified / dist_zero_all\n"
    "print(f'\\n=== 方案1: 所有层统一 K={k_unified} ===')\n"
    "print(f'  distance = {dist_k_unified:.4f}, recovery = {recovery_scheme1:.1%}')\n"
    "\n"
    "# --- 方案2: K 网格 ---\n"
    "k_grid = [0, 16, 32, 64, 128, 192, 256, 384, 512, 640, 704, 736, 768]\n"
    "scheme2 = []\n"
    "for k in k_grid:\n"
    "    d = all_layer_distance(k)\n"
    "    r = 1 - d / dist_zero_all if dist_zero_all > 0 else float('nan')\n"
    "    scheme2.append({'k': k, 'distance': round(d, 4), 'recovery': round(r, 4)})\n"
    "    print(f'  K={k:3d}: distance={d:.4f}, recovery={r:.1%}')\n"
    "scheme2_df = pd.DataFrame(scheme2)\n"
    "\n"
    "# --- 画图 ---\n"
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n"
    "\n"
    "# 左: 方案2 全层恢复曲线\n"
    "ax1.plot(scheme2_df['k'], scheme2_df['recovery'], 'o-', linewidth=2, markersize=6, color='darkred', label='All 12 layers simultaneous')\n"
    "ax1.axhline(0.99, color='gray', linestyle='--', alpha=0.5, label='99% recovered')\n"
    "ax1.axvline(k_unified, color='red', linestyle=':', alpha=0.7, label=f'K_unified={k_unified}')\n"
    "# 叠加各单层曲线做对比\n"
    "colors = plt.cm.coolwarm(np.linspace(0, 1, 12))\n"
    "for layer in all_layers:\n"
    "    single = loss_recovery_metrics[loss_recovery_metrics['layer'] == layer].sort_values('n_components')\n"
    "    ax1.plot(single['n_components'], single['recovery_fraction'], '-', color=colors[layer-1], alpha=0.2, linewidth=0.8)\n"
    "ax1.set_xlabel('K (components per layer)')\n"
    "ax1.set_ylabel('CLS representation recovered')\n"
    "ax1.set_title('Scheme 2: All-layer simultaneous vs single-layer')\n"
    "ax1.legend(fontsize=9)\n"
    "ax1.set_ylim(-0.05, 1.05)\n"
    "\n"
    "# 右: 方案1 对比柱状图 (在 K=K_unified 处)\n"
    "single_at_k = loss_recovery_metrics[\n"
    "    loss_recovery_metrics['n_components'] == k_unified\n"
    "][['layer', 'recovery_fraction']].sort_values('layer')\n"
    "ax2.bar(single_at_k['layer'], single_at_k['recovery_fraction'], alpha=0.5, color='steelblue', label='Single-layer ablation')\n"
    "ax2.bar([13], [recovery_scheme1], alpha=0.7, color='darkred', label='All 12 layers simultaneous')\n"
    "ax2.axhline(0.99, color='gray', linestyle='--', alpha=0.5)\n"
    "ax2.set_xlabel('Layer (13 = all simultaneous)')\n"
    "ax2.set_ylabel(f'Recovery at K={k_unified}')\n"
    "ax2.set_title(f'Scheme 1: Single vs All-layer at K={k_unified}')\n"
    "ax2.legend(fontsize=9)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "display(scheme2_df)\n"
)

with open(NB, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Ensure cell 11 exists
while len(nb["cells"]) < 12:
    nb["cells"].append({
        "cell_type": "code", "id": f"cell-{len(nb['cells'])}",
        "metadata": {}, "execution_count": None, "outputs": [], "source": [],
    })

lines = CELL_SOURCE.strip().split("\n")
nb["cells"][10]["source"] = [line + "\n" for line in lines[:-1]] + [lines[-1]]
nb["cells"][10]["outputs"] = []
nb["cells"][10]["execution_count"] = None
nb["cells"][10]["id"] = "all-layer-ablation"

with open(NB, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print("Cell 11 patched with all-layer ablation experiment")
